export type BriefFormType = {
  id?: number;
  user_id?: number;
  created_at?: string;
  updated_at?: string;
  project_name: string;
  company_avatar?: string;
  company_name?: string;
  company_details?: string;
  project_details?: string;
  product_details?: string;
  product_usp?: string;
  project_goals?: string[];
  project_goals_details?: string;
  project_objectives?: string[];
  brand_strategy?: string;
  brand_message?: string;
  brand_tone?: string;
  target_markets?: string[];
  target_genders?: string[];
  target_ages?: string[];
  target_description?: string;
  ideas_medium?: string[];
  ideas_channels?: string[];
  ideas_quantity: number;
};