export type BriefFormType = {
  id?: number;
  user_id?: number;
  created_at?: string;
  updated_at?: string;
  title: string;
  brief_details?: string;
  company_name?: string;
  company_details?: string;
  company_avatar?: string;
  product_details?: string;
  product_usp?: string;
  strategy?: string;
  message?: string;
  tone_of_voice?: string;
  description?: string;
  goals_details?: string;
  goals?: string[];
  ideas_quantity: number;
};